# Let pre-commit know which hooks this repo provides.

- id: arduino-lint
  name: Arduino Lint
  description: Checks arduino projects for issues and conventions.
  entry: arduino-lint
  language: python
  types: [ino]  # requires identify >= 2.4.3
