# Let pre-commit know which hooks this repo provides.

- id: arduino-lint
  name: Arduino Lint
  description: Checks arduino projects for issues and conventions.
  entry: arduino-lint-hook
  language: python
  pass_filenames: false
- id: arduino-cli
  name: Arduino CLI
  description: Verifies arduino projects can be compiled.
  entry: arduino-cli-hook
  langugage: python
  pass_filenames: false
