name: tests

on:
  - push
  - pull_request

jobs:

  run-test:
    name: ${{ matrix.python-version }}-${{ matrix.build-type }}-${{ matrix.architecture }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        architecture:
          - x64
          - x86

        exclude:
          # linux does not have x86 python.
          - os: "ubuntu-latest"
            architecture: x86

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install depenencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pytest coverage
          python -m pip install -r requirements.txt

      - name: Setup Arduino Lint
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-lint/main/etc/install.sh | sh -s 1.2.0
          echo "${PWD}/bin/" >> $GITHUB_PATH

      - name: Run tests
        run: |
          cd tests/
          python -m pytest -s .
