name: tests

on:
  - push
  - pull_request

jobs:

  run-test:
    name: ${{ matrix.python-version }}-${{ matrix.build-type }}-${{ matrix.architecture }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          # Ignoring windows until I can resolve the path issues.
          # - "windows-latest"
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        architecture:
          - x64
          - x86

        exclude:
          # linux does not have x86 python.
          - os: "ubuntu-latest"
            architecture: x86

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install depenencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pytest coverage
          python -m pip install -r requirements.txt

      - name: Setup Arduino Lint
        shell: bash
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-lint/main/etc/install.sh | sh -s 1.2.0

      - name: Setup Arduino CLI
        shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -s 0.21.1
          bin/arduino-cli core install arduino:avr

      - name: Put tools on path
        shell: bash
        run: echo "${PWD}/bin/" >> $GITHUB_PATH

      - name: Run tests
        run: |
          cd tests/
          python -m pytest -s .
